# Generated by Django 3.2.7 on 2023-01-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0002_signup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='name',
        ),
    ]
