# Generated by Django 3.2.7 on 2023-01-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0003_rename_username_signup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
    ]
